name: Go Docker Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t molidb .

      - name: Run Docker container
        run: |
          docker run -d -p 17233:17233 --name molidb_container molidb
          docker ps -a

      - name: Verify if the service is running
        run: |
          curl -f http://localhost:17233 || exit 1

      - name: Clean up Docker container
        run: |
          docker stop molidb_container
          docker rm molidb_container
