name: Go Docker Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Set up Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew install --cask docker

      - name: Install Docker on Windows
        if: runner.os == 'Windows'
        run: |
          choco install docker-desktop

      - name: Log in to DockerHub (if needed)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t molidb .

      - name: Run Docker container
        run: |
          docker run -d -p 17233:17233 --name molidb_container molidb
          docker ps -a

      - name: Verify if the service is running (optional)
        run: |
          curl -f http://localhost:17233 || exit 1

      - name: Clean up
        run: |
          docker stop molidb_container
          docker rm molidb_container

        run: |
          docker stop molidb_container
          docker rm molidb_container
